version: '1.1'
services:
  client:
    build:
      context: ./frontend_mysql
    ports:
      - "3000:3000"
    container_name: client
    depends_on:
      [backend]

  backend:
    build:
      context: ./backend_mysql
    ports:
      - "8080:8080"
    restart: always
    container_name: backend
    depends_on:
      [db]

  db:
    build:
      context: ./backend_mysql/docker/db
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin

  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    command: ['nginx-debug', '-g', 'daemon off;']
    depends_on:
      [client]

volumes:
  db: {}